version: "3.3"
services:
  rpcserver:
    # 这是 deliver-image.sh 打包的镜像，并上传到私有仓库192.168.0.182
    image: 192.168.0.182:5000/rpcserver:${tag}
    container_name: rpcserver
    environment:
      - TZ=Asia/Shanghai
    #network_mode: host
    #只暴露端口
    ports:
      - "9080:9080"
    deploy:
      replicas: 2
      update_config: # 更新配置
        parallelism: 2 # 并发数
        delay: 15s # 延迟秒数，应大于定时发现的时间间隔
      restart_policy:
        condition: on-failure

    # 由于镜像已经构建过代码，不用重复构建，因此去掉重复代码
    # build: .
    # volumes: # 映射目录， 方便读写
    #   - ./:/opt/rpcserver
    # #command: "/bin/sh", "-c", "while true; do sleep 100; done" # 让进程一直跑, 否则容器会exit
    # entrypoint: /opt/rpcserver/start-rpcserver.sh