# 1 公共配置
__common:
  # 是否调试
  debug: true
  # 指定数据源工厂，需要 IDataSourceFactory 对象，可自定义实现类，但需自己实现根据数据源名来缓存创建好的数据源
  # set dataSourceFactory for Db, it wants IDataSourceFactory's object, you can implements your subclass, but you need to cache dataSource by a name
  dataSourceFactory: net.jkcode.jkmvc.db.DruidDataSourceFactory

# 2 不同数据库的配置
# mysql, 命名: 小写+下划线
default:
  # 主库
  master:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/tracer?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 字段名是下划线命名
    columnUnderline: true
    # 字段名全大写
    columnUpperCase: false
  # 多个从库, 可省略
  slaves:
    -
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/tracer?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

