version: "3.3"
services:
  jksoa-rpc-server:
    # 这是 deliver-image.sh 打包的镜像，并上传到私有仓库192.168.0.182
    image: 192.168.0.182:5000/swarm-discovery:${tag}
    container_name: swarm-discovery
    environment:
      - TZ=Asia/Shanghai
    #network_mode: host
    #只暴露端口
    #ports:
    #  - "9080:9080"
    deploy:
      replicas: 1 # 只需要一个副本
      update_config: # 更新配置
        delay: 10s # 延迟秒数
      restart_policy:
        condition: on-failure

    # 由于镜像已经构建过代码，不用重复构建，因此去掉重复代码
    # build: .
    # volumes: # 映射目录， 方便读写
    #   - ./:/opt/swarm-discovery
    # #command: "/bin/sh", "-c", "while true; do sleep 100; done" # 让进程一直跑, 否则容器会exit
    # entrypoint: /opt/swarm-discovery/start-swarm-discovery.sh